### ISSUE TITLE
Dashboard broken

### ISSUE THREAD

**Issue by robsonpeixoto** [sixpack/sixpack#264]
The dashboard are without CSS and JS files. The UI a completed broken.
Is it a bug or a configuration error? How to fix?

![image](https://cloud.githubusercontent.com/assets/124390/22264805/14b88030-e258-11e6-8436-dcf268da0630.png)

All browser requests:
![image](https://cloud.githubusercontent.com/assets/124390/22265231/e2b6d5b2-e259-11e6-8c6b-ccfb808f36ee.png)

`Dockerfile`
```Dockerfile
FROM python:2.7.9
RUN pip install sixpack==2.3.1
ENTRYPOINT ["gunicorn", "--access-logfile", "-", "-b", "0.0.0.0:5000", "--worker-class=gevent"]
```

`docker-compose.yml`
```yml
version: "2"
services:
  sixpackapi:
    build: .
    command: "-w 8 sixpack.server:start"
    environment:
      - SIXPACK_CONFIG_ENABLED=true
      - SIXPACK_CONFIG_REDIS_PORT=6379
      - SIXPACK_CONFIG_REDIS_HOST=redis
      - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
    links:
    - redis
    ports:
    - "5000:5000"
  sixpackweb:
    build: .
    command: "-w 2 sixpack.web:start"
    environment:
      - SIXPACK_CONFIG_ENABLED=true
      - SIXPACK_CONFIG_REDIS_PORT=6379
      - SIXPACK_CONFIG_REDIS_HOST=redis
      - SIXPACK_CONFIG_REDIS_PREFIX=sixpack
    links:
    - redis
    ports:
    - "5001:5000"
  redis:
    image: redis:3.2.6
```
